name: Test Single Scraper

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
          npm install cheerio

      - name: Run Specific Scraper
        run: |
          node scrapers/skynews.js

      - name: Commit and Push Test XML & Images
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add xml/*.xml images/
          git commit -m "🧪 Test Run: Updated skynews.xml and downloaded images" || true
          
          # This pulls any recent changes you made in the GitHub UI so it doesn't get blocked!
          git pull --rebase origin main 
          
          git push
